#! /usr/bin/env python3

#setting up argparse
import argparse

parser=argparse.ArgumentParser("A program to isolate only the segment of interest")
parser.add_argument("-f", "--file", help="the name of the file to pass through", required=True)
parser.add_argument("-s", "--start", help="starting position", required=True, type=int)
parser.add_argument("-e", "--end", help="ending position", required=True, type=int)
parser.add_argument("-o", "--output", help="output file name", required=True)
parser.add_argument("-h", "--head", help="Sequence header name", required=True)
args = parser.parse_args()

#Reading in the file -> then puts only the lines that have the sequence ID into a new file
with open(args.file, "r") as fh:
  #sets a string where the letters of interest are put
  isolate=""
  #isolate 1 line -- note the file should only be 1 line for this to work
  for line in fh:
    counter=0
    #isolates each letter in the line
    for letter in line:
      counter+=1
      #checks to make sure the letter is within the start and end range
      #adds it to the string if it's in range
      if counter>= args.start and counter<=args.end:
        isolate+=letter
#adds my entire string to a new file
#makes the header line for the sequence so it can be interpreted as a fasta file
header=">" + args.head
with open(args.output, "w") as my_file:
  my_file.write(header+"\n")
  my_file.write(isolate)
